export default {
  OPEN_DIRECTORY: "OPEN_DIRECTORY",
  OPEN_EVENTS: "OPEN_EVENTS",
  OPEN_NEWS: "OPEN_NEWS",
  OPEN_SIGNIN: "OPEN_SIGNIN",
  OPEN_SIGNUP: "OPEN_SIGNUP",
  OPEN_ABOUT: "OPEN_ABOUT",
  OPEN_REGISTRATION: "OPEN_REGISTRATION",
  CREATE_TOKEN: "CREATE_TOKEN"
}
